# Generated by Django 6.0.2 on 2026-04-28 12:51

import django.db.models.deletion
import django.utils.timezone
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_appuser_order_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionCache',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_conditions_hash', models.CharField(db_index=True, max_length=255)),
                ('suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'db_table': 'suggestion_cache',
            },
        ),
    ]
