# Generated by Django 6.0.2 on 2026-04-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_suggestioncache'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.FloatField(default=0.0),
        ),
    ]
